baseURL = "http://gloworm.vision/"
languageCode = "en-us"
title = "Gloworm"
theme = "book"

enableGitInfo = true

[params]
  BookRepo = 'https://github.com/gloworm-vision/gloworm-docs'
  BookMenuBundle = '/menu'